{% set name = "spherical-geometry" %}
{% set version = "1.2.5" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  'sha256': 'facf92dc2e9bd5e110360a3647a26dc0bd02ea612180e24208ce104266ae1310'

build:
  number: 1001
  script: python setup.py install --offline --single-version-externally-managed --record=record.txt
  skip: true  # [win and py3k]

requirements:
  build:
    - python
    - setuptools
    - astropy
  run:
    - python
    - astropy

test:
  imports:
    - spherical_geometry
    - spherical_geometry.utils

about:
  home: http://www.stsci.edu/resources/software_hardware/stsci_python
  license: BSD 3-clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: A Python package for handling spherical polygons that represent arbitrary regions of the sky
  description: |
    The `spherical_geometry` library is a Python package for handling
    spherical polygons that represent arbitrary regions of the sky. It has
    classes for representing and operating on spherical polygons, arbitrary
    areas on the sky sphere enclosed by great circle arcs, and great circle
    arcs.
  doc_url: http://spacetelescope.github.io/spherical_geometry/spherical_geometry/
  dev_url: https://github.com/spacetelescope/spherical_geometry

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - bernie-simon
    - pllim
    - jhunkeler
