{% set name = "spherical-geometry" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: bed481a8b080748bf93434c3b113eae53609a61d0c0694db83c07685b52c3d23

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  skip: true  # [py<39]

requirements:
  build:
    - python {{ python }}                    # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python {{ python }}
    - pip
    - setuptools
    - setuptools_scm
    - astropy
  run:
    - python
    - setuptools
    - astropy
    - numpy >=1.23

test:
  imports:
    - spherical_geometry
    - spherical_geometry.math_util

about:
  home: http://www.stsci.edu/resources/software_hardware/stsci_python
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: A Python package for handling spherical polygons that represent arbitrary regions of the sky
  description: |
    The `spherical_geometry` library is a Python package for handling
    spherical polygons that represent arbitrary regions of the sky. It has
    classes for representing and operating on spherical polygons, arbitrary
    areas on the sky sphere enclosed by great circle arcs, and great circle
    arcs.
  doc_url: http://spacetelescope.github.io/spherical_geometry/spherical_geometry/
  dev_url: https://github.com/spacetelescope/spherical_geometry

extra:
  recipe-maintainers:
    - mwcraig
    - mcara
    - pllim
    - jhunkeler
